package internal

import discord_structs "github.com/WelcomerTeam/Discord/structs"

type Application discord_structs.Application

type ApplicationTeam discord_structs.ApplicationTeam

type ApplicationTeamMember discord_structs.ApplicationTeamMember

type ApplicationCommand discord_structs.ApplicationCommand

type ApplicationCommandOption discord_structs.ApplicationCommandOption

type ApplicationCommandOptionChoice discord_structs.ApplicationCommandOptionChoice

type Interaction discord_structs.Interaction

type InteractionData discord_structs.InteractionData

type InteractionDataOption discord_structs.InteractionDataOption

type InteractionResolvedData discord_structs.InteractionResolvedData

type ApplicationSelectOption discord_structs.ApplicationSelectOption

type Integration discord_structs.Integration

type IntegrationAccount discord_structs.IntegrationAccount

type InteractionComponent discord_structs.InteractionComponent
